### ISSUE TITLE
cannot find package "github.com/weppos/dnscaa"

### ISSUE THREAD

**Issue by Pablohn26** [weppos/dnscaa#1]
It seems build instructions are incomplete. 

After clone this repo, when I type

> go build cmd/digcaa/digcaa.go 

I get 
```
cmd/digcaa/digcaa.go:8:2: cannot find package "github.com/weppos/dnscaa" in any of:
	/usr/lib/golang/src/github.com/weppos/dnscaa (from $GOROOT)
	($GOPATH not set)
```

It seems some variables are not defined.

Could you help me about this issue?

**Comment by weppos** [comment]
It looks like you didn't setup the $GOPATH. Please make sure you cloned it in the appropriate GO directory.
https://golang.org/doc/code.html

**Comment by eapolsniper** [comment]
I had the same issue, mainly due to not knowing Go. Here's how to fix it:

export GOPATH=~/go
go get github.com/weppos/dnscaa

**Comment by guhur** [comment]
I had the same problem, which was solved with a more recent version of `go`

**Comment by andresuchitra** [comment]
continuing this discussion, may I know if Go can automatically download the dependencies? 
we could have cascading dependencies right?

it'd be too troublesome to manually download the the dependencies of a 3rd party project

**Comment by weppos** [comment]
> continuing this discussion, may I know if Go can automatically download the dependencies?
> we could have cascading dependencies right?
> 
> it'd be too troublesome to manually download the the dependencies of a 3rd party project

Go can manage dependencies using Go modules in Go 1.12 or higher.
