### ISSUE TITLE
Why is 8.8.8.8 hard-coded?

### ISSUE THREAD

**Issue by dentarg** [weppos/dnscaa#3]
Looks like Google Public DNS (8.8.8.8) is always used to lookup CAA: https://github.com/weppos/dnscaa/blob/07e0c5ffa15cdde6537da859344d92914587491f/dnscaa.go#L96, is that correct? Why is that? Just because it was the quickest solution, or is there some edge we want to mitigate?

**Comment by weppos** [comment]
It was just the quickest solution at the moment, since it's the resolver I use the most (and I trust the most).

I will happily accept a patch to add a servers list (or a single server) to the resolver struct, and pass the option from the CLI.

**Comment by dentarg** [comment]
What about picking the resolver of the system?

**Comment by weppos** [comment]
I've seen dozens of cases where local resolvers were exposing stale, cached or invalid data. I don't trust local resolvers enough to switch to them by default, and definitely not as part of the package.

The package should accept a server, and then the CLI will be responsible to set it.

**Comment by dentarg** [comment]
Well yeah, I hear you, I can agree with that experience of local resolvers, when you aren't on your own network... :-) But not sure I agree with the solution to it. I've set my local resolver to my own resolver that I use over VPN, so I don't have to deal with crappy local resolvers. I get the benefit from this in every application I use. Hard coding a server to use, or making the user supply the server to use, seems to me like solving the problem on the wrong level. If I would get to decide, I think I would make use the system resolver default, with an option to use any server you want.

By the way, installing `bind` from Homebrew got me a newer `dig` that can understand the CAA record, so this isn't a big deal for me. You can close the issue if you want, the question has been answered.

**Comment by weppos** [comment]
> Hard coding a server to use, or making the user supply the server to use, seems to me like solving the problem on the wrong level. 

I agree hard-coding is an issue. But keep in mind that this package is a library first and foremost (then a CLI tool), hence the library should allow the developer to supply the preferred servers.

The CLI will be responsible for dealing with the various configs.

This will become even more clear in the future as people (as you did) will upgrade their `dig` versions and eventually will be able to use it to query CAA.

**Comment by hopeseekr** [comment]
Don't you see the rampant privacy problems with Google being queried by third parties without your knowledge, informed consent, and going against 5 decades of how DNS server derivation (either via DHCP or static configuration) has been done?

Even if you don't care about the privacy problems, consider that despotic corporations and regimes around the world are using 8.8.8.8 to block / spy on things like VPNs, secure communication lines, etc.

Responsible tech people need to start blocking 8.8.8.8 right now before something like it is used to really further dystopian agendas. Our parents, relatives, and non-technical colleagues have little hope in even detecting these shenanigans, much less blocking them on their own. And if we can't stand unified, who will?

A lesser solution would be to use non-Google public DNS servers, like 1.1.1.1 or 75.75.75.75, OpenDNS etc, but in a random array. A large enough array would limit the privacy leaks somewhat, and it would break this stupid trend of apps hard coding specifically 8.8.8.8. The big problem is that Chrome on Android hard codes 8.8.8.8, too.

**Comment by weppos** [comment]
@hopeseekr I'll be happy to review your PR with the changes required to make the value configurable in the resolver.
